project:
  type: website

website:
  title: "Page AMU, Jérémy Béna : Ressources de cours"
  
  navbar:
    left:
      - coursA.qmd
      - recherche.qmd
    right:
      - about.qmd
      - icon: github
        href: https://github.com/JeremyBena/site_amu
      # - icon: twitter
      #   href: https://twitter.com
format:
  html:
    theme: flatly
    css: styles.css

editor: visual

